# Generated by Django 4.2.6 on 2024-02-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.CharField(auto_created=True, max_length=20),
        ),
    ]
